version: '2'
services:
  wanamu-backend-2:
    build: .
    environment:
        WU_MONGO_PORT: 27017,
        WU_MONGO_DB: wanamu-test,
        WU_MONGO_HOST: mongo
        WU_JWT_SECRET: 12345678,
        WU_REDIS_PORT: 6379,
        WU_REDIS_HOST: redis
        PORT: 3000,
        WU_CPUS: 1,
        WU_APP_NAME: wanamu-backend-2
    depends_on:
      - redis
      - mongo
    ports:
      - "3000"
    links:
      - redis
      - mongo
    dns:
      - 8.8.8.8
  redis:
    image: redis
  mongo:
    image: mongo