version: 2
services:
  redis:
    image: redis
  mongo:
    image: mongo
environment:
    WU_MONGO_PORT: 27017,
    WU_MONGO_DB: wanamu-test,
    WU_JWT_SECRET: 12345678,
    WU_REDIS_PORT: 6379,
    PORT: 9999,
    WU_CPUS: 1,
    WU_APP_NAME: wanamu-backend-2
